spring.application.name=ms-administrador

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rlsuzveutyfpasskdfix
spring.datasource.password=Ns!nqpWK$C8bR$x
spring.datasource.driver-class-name=org.postgresql.Driver


